# =============================================================================
#  /market -- every text of the market preview, Polish and English
#  (Iwakura's Patch 12, point 1K: "Teksty w panelu po polsku; przygotowac
#  klucze tlumaczen jak w edytorze bazy (EN obok PL)"). German and Turkish
#  readers get English, as the database editor's do (editsql/i18n.py): half a
#  translation reads worse than either language. A text the page's script
#  shows is a key here too, handed to it whole in the reader's language.
# =============================================================================

LANGUAGES = ("pl", "en")

TEXTS = {
    # The page and the home page's card
    "title": ("Podgląd rynku", "Market preview"),
    "doc_title": ("Podgląd rynku · Metin2 Singleplayer", "Market preview · Metin2 Singleplayer"),
    "experimental": ("wersja eksperymentalna", "experimental"),
    "card_hint": ("Wszystkie oferty ze sklepów offline ze wszystkich królestw – botów i graczy. Kategorie, "
                  "filtry po poziomie, ulepszeniu i bonusach, okazje cenowe.",
                  "Every offer of the offline shops of all kingdoms – bots' and players'. Categories, filters "
                  "by level, refinement and bonuses, price bargains."),
    "card_open": ("Otwórz podgląd rynku", "Open the market preview"),
    "back": ("← Wróć do panelu", "← Back to the panel"),
    "not_here": ("Podgląd rynku czyta sklepy offline linii 2.x (mt2009); ten serwer ich nie ma.",
                 "The market preview reads the offline shops of the 2.x line (mt2009); this server has none."),
    # The top bar
    "search_ph": ("Szukaj przedmiotu…", "Search for an item…"),
    "offers_n": ("{n} ofert", "{n} offers"),
    "data_from": ("Dane z: {t}", "Data from: {t}"),
    "refresh": ("odśwież", "refresh"),
    "building": ("Buduję migawkę rynku – to potrwa kilka sekund…", "Building the market snapshot – a few seconds…"),
    "sort": ("Sortowanie", "Sort"),
    "sort_deals": ("Najlepsze okazje", "Best bargains"),
    "sort_price_asc": ("Cena: od najniższej", "Price: lowest first"),
    "sort_price_desc": ("Cena: od najwyższej", "Price: highest first"),
    "sort_unit_asc": ("Cena za sztukę: od najniższej", "Unit price: lowest first"),
    "sort_plus_desc": ("Ulepszenie: od najwyższego", "Refinement: highest first"),
    "sort_level_desc": ("Poziom przedmiotu: od najwyższego", "Item level: highest first"),
    "sort_level_asc": ("Poziom przedmiotu: od najniższego", "Item level: lowest first"),
    "sort_bonus_count": ("Najwięcej bonusów", "Most bonuses"),
    "sort_tier_sum": ("Najwyższa suma tierów bonusów", "Highest bonus tier sum"),
    "sort_newest": ("Najnowsze wystawienia", "Newest listings"),
    "per_page": ("Na stronie", "Per page"),
    "character": ("Postać", "Character"),
    "character_none": ("— bez postaci —", "— no character —"),
    "character_hint": ("Twoja postać na koncie gracza: klasa i poziom do plakietek, cel przycisku TP.",
                       "Your character on a player's account: its class and level for the badges, the TP's target."),
    "filters_toggle": ("Kategorie i filtry", "Categories and filters"),
    # Categories
    "categories": ("KATEGORIE", "CATEGORIES"),
    "cat_all": ("Wszystko", "Everything"),
    # Filters
    "filters": ("FILTRY", "FILTERS"),
    "f_price": ("Cena", "Price"),
    "f_from": ("od", "from"),
    "f_to": ("do", "to"),
    "f_price_hint": ("np. 500k, 1.5kk", "e.g. 500k, 1.5kk"),
    "f_unit": ("Cena za sztukę zamiast ceny linii", "Unit price instead of the line's price"),
    "f_level": ("Poziom przedmiotu", "Item level"),
    "f_level_from": ("od lv", "from lv"),
    "f_level_to": ("do lv", "to lv"),
    "f_plus": ("Ulepszenie", "Refinement"),
    "f_any": ("dowolne", "any"),
    "f_class": ("Klasa", "Class"),
    "f_class_all": ("wszystkie", "all"),
    "f_mine": ("tylko dla mojej postaci", "only for my character"),
    "f_bonus": ("Bonus", "Bonus"),
    "f_bonus_none": ("— bonus —", "— bonus —"),
    "f_bonus_min": ("min. wartość", "min. value"),
    "f_bonus_add": ("+ dodaj bonus", "+ add a bonus"),
    "f_nbmin": ("Min. bonusów", "Min. bonuses"),
    "f_maxonly": ("Tylko z bonusem maksymalnym", "Only with a maximum bonus"),
    "f_nmaxmin": ("min. bonusów maksymalnych", "min. maximum bonuses"),
    "f_avg": ("Średnie obrażenia (ŚR)", "Average damage (AVG)"),
    "f_skl": ("Obrażenia umiejętności (UM)", "Skill damage (SKL)"),
    "f_ks": ("Kamienie duszy w przedmiocie", "Soul stones in the item"),
    "f_ks_any": ("dowolne", "any"),
    "f_ks_has": ("ma KD", "has a soul stone"),
    "f_emp": ("Królestwo", "Kingdom"),
    "f_emp_all": ("wszystkie", "all"),
    "f_seller": ("Sprzedawca", "Seller"),
    "f_seller_all": ("wszyscy", "everybody"),
    "f_seller_bot": ("tylko boty", "bots only"),
    "f_seller_person": ("tylko gracze", "players only"),
    "f_sname": ("nazwa sprzedawcy", "seller's name"),
    "f_deals": ("Tylko okazje", "Bargains only"),
    "f_dmin": ("co najmniej X% taniej", "at least X% cheaper"),
    "f_hideslip": ("Ukryj „ludzką pomyłkę”", "Hide \"human slips\""),
    "f_hideslip_hint": ("Oferty oznaczone jako błąd cenowy (Patch 4/5).", "Offers marked as a price slip (Patch 4/5)."),
    "f_expired": ("Pokaż wygasłe sklepy", "Show expired shops"),
    "apply": ("Zastosuj", "Apply"),
    "clear_filters": ("Wyczyść filtry", "Clear filters"),
    "bad_value": ("Błędna wartość – filtr nie jest wysyłany.", "Wrong value – this filter is not sent."),
    "bad_range": ("„do” jest mniejsze niż „od”.", "\"to\" is less than \"from\"."),
    "only_shop": ("Tylko sklep: {name}", "Only the shop: {name}"),
    "only_item": ("Tylko przedmiot: {name}", "Only the item: {name}"),
    "remove": ("usuń", "remove"),
    "empires": (("Shinsoo", "Chunjo", "Jinno"), ("Shinsoo", "Chunjo", "Jinno")),
    "classes": (("Wojownik", "Ninja", "Sura", "Szaman"), ("Warrior", "Ninja", "Sura", "Shaman")),
    # An offer
    "from_level": ("od {n} lv", "from lv {n}"),
    "not_for_you": ("nie dla Twojej postaci", "not for your character"),
    "all_classes": ("wszystkie klasy", "all classes"),
    "bonuses_n": ("{n} bonusów", "{n} bonuses"),
    "bonuses_1": ("1 bonus", "1 bonus"),
    "bonuses_few": ("{n} bonusy", "{n} bonuses"),
    "no_bonuses": ("bez bonusów", "no bonuses"),
    "pve_pvp": ("PvE {a} / PvP {b}", "PvE {a} / PvP {b}"),
    "avg": ("ŚR", "AVG"),
    "skl": ("UM", "SKL"),
    "stones": ("KD", "Soul stones"),
    "yang": ("yang", "yang"),
    "per_unit": ("{p} yang / szt.", "{p} yang / pc."),
    "deal": ("Okazja: {n}% taniej niż zwykle", "Bargain: {n}% cheaper than usual"),
    "deal_suspect": ("Bardzo nisko – możliwy błąd ceny albo słaby przedmiot",
                     "Very low – maybe a price slip, or a weak item"),
    "ref_price": ("Cena odniesienia: {p} yang / szt.", "Reference price: {p} yang / pc."),
    "dearer": ("{n}% drożej niż zwykle", "{n}% dearer than usual"),
    "shop_closed": ("sklep zamknięty", "shop closed"),
    "slip": ("ludzka pomyłka", "human slip"),
    "tp": ("TP", "TP"),
    "tp_title": ("Przenieś moją postać do tego sklepu", "Take my character to this shop"),
    "compare_pick": ("Zaznacz do porównania", "Pick to compare"),
    "seller_title": ("Pokaż cały towar tego sklepu", "Show this shop's whole stock"),
    "item_title": ("Pokaż wszystkie oferty tego przedmiotu i wykres ceny", "Show every offer of this item and its price chart"),
    "map_ch": ("{map} · CH{ch}", "{map} · CH{ch}"),
    "map_n": ("Mapa {n}", "Map {n}"),
    # The tooltip
    "tt_level": ("Wymagany poziom: {n}", "Required level: {n}"),
    "tt_attack": ("Wartość ataku: {a} - {b}", "Attack value: {a} - {b}"),
    "tt_magic": ("Wartość ataku magicznego: {a} - {b}", "Magic attack value: {a} - {b}"),
    "tt_speed": ("Szybkość ataku: +{n}%", "Attack speed: +{n}%"),
    "tt_defence": ("Obrona: {n}", "Defence: {n}"),
    "tt_classes": ("Klasa: {c}", "Class: {c}"),
    # Lists
    "empty": ("Brak ofert dla tych filtrów", "No offers for these filters"),
    "load_error": ("Nie udało się wczytać ofert. Spróbuj ponownie.", "The offers could not be loaded. Try again."),
    "retry": ("Spróbuj ponownie", "Try again"),
    "too_fast": ("Za dużo zapytań naraz – chwila przerwy.", "Too many requests at once – a short pause."),
    "login": ("Sesja panelu wygasła – zaloguj się ponownie.", "The panel's session has expired – log in again."),
    "page_prev": ("‹ Poprzednia", "‹ Previous"),
    "page_next": ("Następna ›", "Next ›"),
    "page_of": ("Strona {a} z {b}", "Page {a} of {b}"),
    # The chart
    "chart_title": ("Cena za sztukę z ostatnich 7 dni (mediana godziny)", "Unit price over the last 7 days (hourly median)"),
    "chart_none": ("Za mało historii na wykres – panel zbiera ceny od chwili uruchomienia.",
                   "Not enough history for a chart yet – the panel collects prices from its start."),
    # Comparison
    "compare": ("Porównaj ({n})", "Compare ({n})"),
    "compare_title": ("Porównanie ofert", "Offers compared"),
    "compare_close": ("Zamknij", "Close"),
    "compare_clear": ("Odznacz wszystkie", "Unpick all"),
    "compare_max": ("Porównać można do 4 ofert.", "Up to 4 offers can be compared."),
    "c_plus": ("Ulepszenie", "Refinement"),
    "c_level": ("Poziom", "Level"),
    "c_bonuses": ("Bonusy", "Bonuses"),
    "c_price": ("Cena", "Price"),
    "c_deal": ("Okazja", "Bargain"),
    "c_seller": ("Sprzedawca", "Seller"),
    # TP
    "tp_need_char": ("Wybierz najpierw swoją postać (lista „Postać” nad ofertami).",
                     "Pick your character first (the \"Character\" list above the offers)."),
    "tp_sending": ("Wysyłam zlecenie do serwera gry…", "Sending the order to the game server…"),
    "tp_waiting": ("Czekam na odpowiedź rdzenia gry ({n} s)…", "Waiting for the game core's answer ({n} s)…"),
    "tp_done": ("Przeniesiono do sklepu: {shop}", "Taken to the shop: {shop}"),
    "tp_not_allowed": ("Ta postać nie jest postacią gracza – panel przenosi tylko Twoje postacie.",
                       "This is no player's character – the panel moves only your own characters."),
    "tp_no_shop": ("Tego sklepu już nie ma.", "This shop is gone."),
    "tp_shop_closed": ("Sklep jest zamknięty (skończył mu się czas).", "The shop is closed (its time ran out)."),
    "tp_other_channel": ("Sklep stoi na CH{ch} – zmień kanał w grze i kliknij ponownie.",
                         "The shop stands on CH{ch} – change the channel in the game and click again."),
    "tp_dead": ("Postać jest martwa.", "The character is dead."),
    "tp_dungeon": ("Postać jest w lochu albo w instancji – teleport niemożliwy.",
                   "The character is in a dungeon or an instance – no teleport."),
    "tp_guild_war": ("Postać jest na wojnie gildii – teleport niemożliwy.",
                     "The character is in a guild war – no teleport."),
    "tp_combat": ("Postać jest w walce (obrażenia w ostatnich 10 s) – spróbuj za chwilę.",
                  "The character is fighting (damage in the last 10 s) – try again in a moment."),
    "tp_busy": ("Postać handluje albo ma otwarte okno (sklep, magazyn, kowal) – zamknij je i spróbuj ponownie.",
                "The character is trading or has a window open (a shop, the storeroom, the blacksmith) – close it "
                "and try again."),
    "tp_cooldown": ("Między teleportami musi minąć 30 s – spróbuj za {n} s.",
                    "30 s must pass between teleports – try again in {n} s."),
    "tp_no_gold": ("Postać nie ma tyle yang, ile kosztuje teleport ({cost}).",
                   "The character does not have the teleport's fare ({cost} yang)."),
    "tp_bad_args": ("Złe dane zlecenia – odśwież stronę.", "Wrong order data – reload the page."),
    "tp_failed": ("Serwer gry odmówił teleportu – spróbuj ponownie.", "The game server refused the teleport – try again."),
    "tp_offline": ("Twoja postać nie jest teraz w grze (albo rdzeń gry nie odpowiedział w 15 s).",
                   "Your character is not in the game now (or the game core did not answer within 15 s)."),
    "tp_not_person": ("Wybierz swoją postać z listy – panel przenosi tylko postacie graczy.",
                      "Pick your character from the list – the panel moves only players' characters."),
    "tp_not_here": ("TP działa tylko na linii 2.x (mt2009).", "The TP works on the 2.x line (mt2009) only."),
    "tp_history": ("Historia teleportów", "Teleport history"),
    "tp_history_none": ("Jeszcze żadnego.", "None yet."),
    "tp_cost": ("Koszt teleportu (yang, 0 = wyłączony)", "Teleport fare (yang, 0 = off)"),
    "tp_cost_save": ("Zapisz", "Save"),
    "tp_cost_saved": ("Zapisano koszt teleportu: {cost}.", "Teleport fare saved: {cost}."),
    "tp_settings": ("Ustawienia TP", "TP settings"),
    "tp_waiting_word": ("czeka", "waiting"),
}


def text(key, language):
    pair = TEXTS[key]
    return pair[0] if language == "pl" else pair[1]


def for_language(language):
    """Every text in one language, for the page's script."""
    return {key: (pair[0] if language == "pl" else pair[1]) for key, pair in TEXTS.items()}
